export const BRAINTREE_OPTIONS_PROVIDER = 'BRAINTREE_OPTIONS_PROVIDER';
export const BRAINTREE_WEBHOOK_SUBSCRIPTION_CANCELED = 'subscription_canceled';
export const BRAINTREE_WEBHOOK_SUBSCRIPTION_EXPIRED = 'subscription_expired';
