export const BRAINTREE_PROVIDER = 'BRAINTREE_PROVIDER';
export const BRAINTREE_OPTIONS_PROVIDER = 'BRAINTREE_OPTIONS_PROVIDER';
export const BRAINTREE_WEBHOOK_SUBSCRIPTION_CANCELED = 'BRAINTREE_WEBHOOK_SUBCRIPTION_CANCELED';
export const BRAINTREE_WEBHOOK_SUBSCRIPTION_EXPIRED = 'BRAINTREE_WEBHOOK_SUBSCRIPTION_EXPIRED';
