export const BRAINTREE_OPTIONS_PROVIDER = 'BRAINTREE_OPTIONS_PROVIDER';
export const BRAINTREE_WEBHOOK_SUBSCRIPTION_CANCELED = 'subscription_canceled';
export const BRAINTREE_WEBHOOK_SUBSCRIPTION_EXPIRED = 'subscription_expired';
export const BRAINTREE_WEBHOOK_PROVIDERS = 'BRAINTREE_WEBHOOK_PROVIDERS';
export const BRAINTREE_WEBHOOK_METHODS = 'BRAINTREE_WEBHOOK_METHODS';
export const BRAINTREE_WEBHOOK_METHOD = 'BRAINTREE_WEBHOOK_METHOD';
export const BRAINTREE_WEBHOOK_PROVIDER = 'BRAINTREE_WEBHOOK_PROVIDER';